version: '3'
services:
    shindig-server:
        container_name: shindig-server
        restart: always
        build: ./server
        ports:
            - '3000:3000'
        depends_on:
            - db
    db:
        container_name: db
        image: mongo
        ports:
            - '27017:27017'
    db-seed:
        container_name: db-seed
        build: ./mongo-seed
        depends_on:
            - db
    client:
        container_name: seek-truth
        restart: always
        build: ./client
        ports:
            - '8080:8080'
        depends_on:
            - shindig-server