version: '3'
services:
    shindig-server:
        container_name: ST-server
        restart: always
        build: ./server
        ports:
            - '3000:3000'
        depends_on:
            - db
    db:
        container_name: ST-mongo
        image: mongo
        ports:
            - '27017:27017'
    db-seed:
        container_name: ST-seed
        build: ./mongo-seed
        depends_on:
            - db
    client:
        container_name: ST-client
        restart: always
        build: ./client
        ports:
            - '8080:8080'
        depends_on:
            - shindig-server